### ISSUE TITLE
Configurable not sending an actual email in development / non-production environments

### ISSUE THREAD

**Issue by kendaleiv** [ritterim/silverpop-dotnet-api#35]
It would be useful to have a way to simulate sending an email during development time, rather than sending an actual email.

Many times during development you don't want to send a _real_ email. But, you may want to test that the application code paths are followed that would lead to an email being sent when not debugging locally.

You _could_ build this infrastructure into an application as necessary (which, we've done), but it might be nice to have this baked into this library.

**Comment by kendaleiv** [comment]
Opinions on how to surface this notification to the user? In one of our applications we're using [khalidabuhakmeh/MvcFlash2](https://github.com/khalidabuhakmeh/MvcFlash2), but this is probably an inappropriate dependency for this public repository.

In ASP.NET 5, we could surface the development time would-have-sent-this-email via http://docs.asp.net/en/latest/fundamentals/logging.html or similar.

For the current version of ASP.NET, how should we do this? Send it to **Debug** in the **Output** window in Visual Studio?

@billboga @jrusbatch @khalidabuhakmeh

**Comment by khalidabuhakmeh** [comment]
We could create a Middleware component that registers an endpoint, and then a frontend component that polls that endpoint for mail messages. Maybe we could even call it `Mailman`?

All the developer would have to do is inject a wrapped version for their email. Which you may be able to toggle the real behavior on or off from the client?

**Comment by kendaleiv** [comment]
Also, this functionality should probably handle a QA/non production environment not sending an _actual_ email, too. Perhaps **Debug** in the **Output** window or the ASP.NET 5 logging isn't the best, since it doesn't cover that use case, as that wouldn't be visible to a user in the browser.

**Comment by kendaleiv** [comment]
Per out-of-this-issue discussion we're going to look into tracing when not sending a _actual_ email.

If the sending of _actual_ email is disabled in a deployed environment http://getglimpse.com/Docs/Trace-Tab could be used to access the tracing details, if necessary.

**Comment by kendaleiv** [comment]
Upon further reflection, I'm hesitant to add this as a primary construct into the main NuGet package.

However, adding tracing for the events taking place, especially (or, perhaps even solely) in [SilverpopCommunicationsClient](https://github.com/ritterim/silverpop-dotnet-api/blob/master/src/Silverpop.Client/SilverpopCommunicationsClient.cs) might be useful for developers.

**Comment by kendaleiv** [comment]
I'm going to close this for now. `virtual` methods were added to `TransactClient` in #37, which enales some additional flexibility.

We could look at this again in the future, if necessary.
