### ISSUE TITLE
Calling AddRecipient with ListID

### ISSUE THREAD

**Issue by wclifton87** [ritterim/silverpop-dotnet-api#38]
This api looks really cool.  However, I need to call the AddRecipient method with a ListID (not a campaign id).  Also, some of the other datapoints on the AddRecipient method need to be set (such as UPDATE_IF_FOUND, ALLOW_HTML, etc).  Does your api support this?
Thanks!

**Comment by kendaleiv** [comment]
This API currently supports sending messages only. It does not support adding recipients to lists on Silverpop.

While I don't know the authentication requirements for calling that endpoint off-hand (user/pass, OAuth, etc.), [src/Silverpop.Client/SilverpopCommunicationsClient.cs](https://github.com/ritterim/silverpop-dotnet-api/blob/master/src/Silverpop.Client/SilverpopCommunicationsClient.cs) and its dependencies may possibly be of use to you.
