### ISSUE TITLE
SendMessageBatch raising a "No such file" exception

### ISSUE THREAD

**Issue by airamez** [ritterim/silverpop-dotnet-api#41]
I fixed it by removing the 'temp/' string from the file path.
Inside the method Silverpop.Client.TransactClient.SendMessageBatch there are two references for "transact/temp/" and when I removed the "temp/" it worked like a charm. I didn't try to commit any changes because maybe the issue just happened with my Silverpop Configuration.
Previous code
121                    silverpop.SftpGzipUpload(
122                       encodedMessage,
123                        "transact/temp/" + filename);

125                    silverpop.SftpMove(
126                       "transact/temp/" + filename,
127                        "transact/inbound/" + filename);

Code after the fix
121                    silverpop.SftpGzipUpload(
122                       encodedMessage,
123                        "transact/" + filename);

125                    silverpop.SftpMove(
126                       "transact/" + filename,
127                        "transact/inbound/" + filename);

**Comment by kendaleiv** [comment]
This may have been resolved in [2.0.4](https://www.nuget.org/packages/silverpop-dotnet-api/2.0.4) by creating a temp folder if it does not exist. If you're still seeing an issue let us know.
