### ISSUE TITLE
Add `Renci.SshNet` Binding Redirects

### ISSUE THREAD

**Issue by khalidabuhakmeh** [ritterim/silverpop-dotnet-api#48]
`Renci.SshNet` is required but does not properly do binding redirects. This can cause an issue with the latest version. This package uses `2013.4.7.0` currently.

```
  <package id="SSH.NET" version="2013.4.7" targetFramework="net45" />
```

**Comment by madushann** [comment]
do you have any update with this, currently we are having this with latest Ranci.SshNet
