### ISSUE TITLE
AccessTokenProvider does not return its locally stored current access token until it has expired.

### ISSUE THREAD

**Issue by carmbrester** [ritterim/silverpop-dotnet-api#56]
The logic in the AccessTokenProvider looks to be inverted for deciding whether to return the current access token...

`if (_currentAccessToken != null &&
        _currentAccessTokenExpiresAt < DateTime.UtcNow.AddMinutes(-5))
{
    return _currentAccessToken;
}`

When I run this, I see continual requests for new access tokens even though the current access token may still be 4 hours away from expiring. I think the following might be more correct...

`if (_currentAccessToken != null &&
        _currentAccessTokenExpiresAt > DateTime.UtcNow.AddMinutes(5))
{
    return _currentAccessToken;
}`

**Comment by kendaleiv** [comment]
Thanks! A fix was released in https://www.nuget.org/packages/silverpop-dotnet-api/2.0.1.
