### ISSUE TITLE
Batch Using Oauth

### ISSUE THREAD

**Issue by Fbiss** [ritterim/silverpop-dotnet-api#71]
First off, thank you for this project!

The current project does not support Batching with oauth, but i was wondering if the code could be updated to support ftp  with the username: oauth , password: access_token  method as documented in the below link.
https://www.ibm.com/support/knowledgecenter/en/SSWU4L/Data/imc_Data/Data_q_a_watson_assistant/Authenticate_to_FTP_with_OAuth.html

**Comment by Fbiss** [comment]
Thanks @kendaleiv

**Comment by kendaleiv** [comment]
@Fbiss Would you be able to test https://www.nuget.org/packages/silverpop-dotnet-api/2.1.0-alpha0001? If it looks good we can move forward with a non-alpha build. I'm not certain it'll work, so it might need some refinement.

**Comment by Fbiss** [comment]
I confirmed this working with using TransactClient.CreateOAuthOnly, and sending 5001 messages (to send two batch files)

![silverpopgithub1](https://user-images.githubusercontent.com/8697449/48427674-43b5b700-e737-11e8-9a2e-9e51efe0de8b.png)

Everything looks good in my testing

**Comment by kendaleiv** [comment]
Thanks! Released in https://www.nuget.org/packages/silverpop-dotnet-api/2.1.0.
