### ISSUE TITLE
Newtonsoft update to 10.0.0.0

### ISSUE THREAD

**Issue by Fbiss** [ritterim/silverpop-dotnet-api#76]
My project in which i'm going to use Silverpop api already has Version 10.0.0.0 of Newtownsoft. I cant downgrade. Can the Newtownsoft dependency be updated to work with 10?

{"Could not load file or assembly 'Newtonsoft.Json, Version=9.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)":"Newtonsoft.Json, Version=9.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed"}

**Comment by kendaleiv** [comment]
You may need to add a binding redirect to your project. This library should support `Newtonsoft.Json` `9.0.1` or later per the nuspec.

**Comment by Fbiss** [comment]
@kendaleiv You are correct. I incorrectly was looking at the app.config the library is referenced in and saw that it had the binding direct, but our tester application the runs that process didn't and thats where it was having a issue.

Sorry for false alarm.

**Comment by kendaleiv** [comment]
No worries, glad I could help!
